// Command gen-rbac-bundle generates an OPA Rego policy file (rbac.rego) that
// encodes the identity-auth RBAC model: the fixed role→permission mapping and
// a scope-intersection decision rule. The api-gateway loads the generated
// bundle and asks `data.identity_auth.authz.allow` for allow/deny decisions.
//
// Usage:
//
//	gen-rbac-bundle [-out rbac.rego]
//
// The output is a self-contained Rego module. The role→permission table is
// emitted as a `data` block from the canonical `rolePermissions` map defined
// in the parent package's rbac.go (mirrored here to avoid an import cycle).
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

// rolePermissions mirrors the canonical map in identity-auth/rbac.go. It is
// duplicated here so this command has no dependency on the service's
// package main. A unit test in the parent package (TestGenRBACBundleMatches)
// asserts the two stay in sync.
var rolePermissions = map[string][]string{
	"user":          {"profile:read", "profile:write", "session:create", "session:read", "session:delete"},
	"partner_admin": {"keys:create", "keys:read", "keys:rotate", "keys:revoke", "partner:read", "partner:write"},
	"partner_api":   {"keys:read", "partner:read"},
	"support":       {"users:read", "session:read"},
	"compliance":    {"users:read", "audit:read"},
	"ops":           {"users:unlock", "session:read", "audit:read"},
	"admin":         {"*"},
}

func main() {
	out := flag.String("out", "rbac.rego", "output Rego file path")
	flag.Parse()

	if err := writeBundle(*out); err != nil {
		fmt.Fprintf(os.Stderr, "gen-rbac-bundle: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s\n", *out)
}

// writeBundle renders the Rego bundle to the given path. It is exported via
// the package so the parent package's test can call it without shelling out.
func writeBundle(path string) error {
	rego := generateRego()
	return os.WriteFile(path, []byte(rego), 0o644)
}

// generateRego returns the full Rego module text.
func generateRego() string {
	var b strings.Builder
	b.WriteString("# GENERATED BY cmd/gen-rbac-bundle — DO NOT EDIT BY HAND.\n")
	b.WriteString("# Encodes the identity-auth RBAC model for the api-gateway OPA sidecar.\n")
	b.WriteString("package identity_auth\n\n")
	b.WriteString("# role_permissions is the fixed role → permission set. The `admin` role\n")
	b.WriteString("# carries the wildcard `*` permission.\n")
	b.WriteString("role_permissions := {\n")

	roles := sortedRoles()
	for _, role := range roles {
		perms := rolePermissions[role]
		sort.Strings(perms)
		fmt.Fprintf(&b, "\t%q: %s,\n", role, regoSet(perms))
	}
	b.WriteString("}\n\n")

	b.WriteString("# bindings is provided at query time by the api-gateway (from the\n")
	b.WriteString("# identity-auth /v1/role-bindings endpoint). Each binding is:\n")
	b.WriteString("#   { \"subject\": \"...\", \"role\": \"...\", \"scope_type\": \"...\", \"scope_id\": \"...\" }\n")
	b.WriteString("bindings := []  # populated at eval time via input.bindings\n\n")

	b.WriteString("# role_grants reports whether the given role permits the action.\n")
	b.WriteString("# The `admin` role's `*` wildcard matches any action.\n")
	b.WriteString("role_grants(role, action) {\n")
	b.WriteString("\tperm := role_permissions[role][_]\n")
	b.WriteString("\tperm == \"*\"\n")
	b.WriteString("}\n\n")
	b.WriteString("role_grants(role, action) {\n")
	b.WriteString("\tperm := role_permissions[role][_]\n")
	b.WriteString("\tperm == action\n")
	b.WriteString("}\n\n")

	b.WriteString("# scope_matches reports whether the binding's scope intersects the\n")
	b.WriteString("# requested resource scope. A binding with an empty scope_id is\n")
	b.WriteString("# global and matches any resource; otherwise the scope_id must equal\n")
	b.WriteString("# the resource (or be a prefix when scope_type=partner).\n")
	b.WriteString("scope_matches(binding, resource) {\n")
	b.WriteString("\tbinding.scope_id == \"\"\n")
	b.WriteString("}\n\n")
	b.WriteString("scope_matches(binding, resource) {\n")
	b.WriteString("\tbinding.scope_id == resource\n")
	b.WriteString("}\n\n")
	b.WriteString("scope_matches(binding, resource) {\n")
	b.WriteString("\tbinding.scope_type == \"partner\"\n")
	b.WriteString("\tstartswith(resource, binding.scope_id + \"/\")\n")
	b.WriteString("}\n\n")

	b.WriteString("# allow is the top-level decision rule consumed by the api-gateway.\n")
	b.WriteString("# input is expected to be: { \"subject\": \"...\", \"action\": \"...\", \"resource\": \"...\" }\n")
	b.WriteString("# and the gateway supplies bindings via data.identity_auth.bindings.\n")
	b.WriteString("allow {\n")
	b.WriteString("\tbinding := bindings[_]\n")
	b.WriteString("\tbinding.subject == input.subject\n")
	b.WriteString("\trole_grants(binding.role, input.action)\n")
	b.WriteString("\tscope_matches(binding, input.resource)\n")
	b.WriteString("}\n\n")

	b.WriteString("# deny_reasons is a set of human-readable reasons for a deny decision.\n")
	b.WriteString("deny_reasons[reason] {\n")
	b.WriteString("\tnot allow\n")
	b.WriteString("\treason := sprintf(\"no binding grants %v on %v for subject %v\", [input.action, input.resource, input.subject])\n")
	b.WriteString("}\n")

	return b.String()
}

// sortedRoles returns the role names in deterministic order.
func sortedRoles() []string {
	roles := make([]string, 0, len(rolePermissions))
	for r := range rolePermissions {
		roles = append(roles, r)
	}
	sort.Strings(roles)
	return roles
}

// regoSet renders a slice of strings as a Rego set literal: {"a", "b"}.
func regoSet(perms []string) string {
	quoted := make([]string, len(perms))
	for i, p := range perms {
		quoted[i] = fmt.Sprintf("%q", p)
	}
	return "{" + strings.Join(quoted, ", ") + "}"
}